-- Appointment tablosunu düzelt ve eksik kolonları ekle

-- Önce mevcut tabloyu kontrol et
DESCRIBE appointments;

-- Eksik kolonları ekle
ALTER TABLE appointments 
ADD COLUMN IF NOT EXISTS age INTEGER,
ADD COLUMN IF NOT EXISTS gender INTEGER,
ADD COLUMN IF NOT EXISTS height DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS weight DECIMAL(6,2),
ADD COLUMN IF NOT EXISTS ap_hi INTEGER,
ADD COLUMN IF NOT EXISTS ap_lo INTEGER,
ADD COLUMN IF NOT EXISTS cholesterol INTEGER,
ADD COLUMN IF NOT EXISTS gluc INTEGER,
ADD COLUMN IF NOT EXISTS smoke INTEGER,
ADD COLUMN IF NOT EXISTS alco INTEGER,
ADD COLUMN IF NOT EXISTS active INTEGER,
ADD COLUMN IF NOT EXISTS risk_score DECIMAL(10,4),
ADD COLUMN IF NOT EXISTS priority_score DECIMAL(10,4),
ADD COLUMN IF NOT EXISTS prediction_label INTEGER,
ADD COLUMN IF NOT EXISTS prediction_probability DECIMAL(10,4),
ADD COLUMN IF NOT EXISTS model_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'normal',
ADD COLUMN IF NOT EXISTS queue_position INTEGER,
ADD COLUMN IF NOT EXISTS appointment_date DATETIME,
ADD COLUMN IF NOT EXISTS assigned_at DATETIME,
ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Tablo yapısını kontrol et
DESCRIBE appointments;
